# Generated by Django 3.0.3 on 2020-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200225_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], max_length=200, null=True, verbose_name='запись'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='описание'),
        ),
    ]
